name: Code Linter

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --no-cache-dir uv
          uv pip install --no-cache-dir flake8 pylint vulture -r requirements.txt -qq --system

      - name: Run flake8
        run: flake8 .
        continue-on-error: true

      - name: Run PyLint
        run: pylint .
        continue-on-error: true

      - name: Run Vulture
        run: vulture .
        continue-on-error: true
