name: Тест CLI скриптов

on:
  push:
    branches:
      - PolGen-Lite-dev
  pull_request:
    branches:
      - PolGen-Lite-dev

jobs:
  rvc_cli:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']

    steps:
    - name: Проверка кода
      uses: actions/checkout@v4

    - name: Настройка Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Установка зависимостей
      run: |
        pip install --upgrade pip==23.1
        pip install --no-cache-dir -r requirements.txt

    - name: Установка ffmpeg
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg

    - name: Установка активов и моделей
      run: |
        python download_models.py
        mkdir -p models/rvc_models/Tsoi
        wget https://huggingface.co/Politrees/Victor_Tsoi/resolve/main/model.index -O models/rvc_models/Tsoi/model.index
        wget https://huggingface.co/Politrees/Victor_Tsoi/resolve/main/model.pth -O models/rvc_models/Tsoi/model.pth

    - name: Установка аудио для теста
      run: |
        mkdir -p audio
        wget https://huggingface.co/Politrees/audio_for_test/resolve/main/BritishEnglishUKTest5.mp3 -O audio/test.mp3

    - name: Запуск скрипта
      run: |
        python3 -m rvc.cli.rvc_cli -i audio/test.mp3 -d Tsoi -p 0 -ir 0 -fr 3 -rms 0.25 -m "rmvpe+" -hop 32 -pro 0.33 -f0min 1 -f0max 1100 -f "mp3"

  tts_cli:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']

    steps:
    - name: Проверка кода
      uses: actions/checkout@v4

    - name: Настройка Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Установка зависимостей
      run: |
        pip install --upgrade pip==23.1
        pip install --no-cache-dir -r requirements.txt

    - name: Установка ffmpeg
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg

    - name: Установка активов и моделей
      run: |
        python download_models.py
        mkdir -p models/rvc_models/Tsoi
        wget https://huggingface.co/Politrees/Victor_Tsoi/resolve/main/model.index -O models/rvc_models/Tsoi/model.index
        wget https://huggingface.co/Politrees/Victor_Tsoi/resolve/main/model.pth -O models/rvc_models/Tsoi/model.pth

    - name: Запуск скрипта
      run: |
        python3 -m rvc.cli.edge_tts_cli -i "e" -d Tsoi -v "en-US-GuyNeural" -p 0 -ir 0 -fr 3 -rms 0.25 -m "rmvpe+" -hop 32 -pro 0.33 -f0min 1 -f0max 1100 -f "mp3"
