name: Check Links

on:
  push:
    branches:
      - dev/PolGen-Lite
  pull_request:
    branches:
      - dev/PolGen-Lite

jobs:
  check-links:
    runs-on: ubuntu-latest

    steps:
    - name: Проверка кода
      uses: actions/checkout@v4

    - name: Настройка Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Установка зависимостей
      run: |
        pip install --upgrade pip==23.1
        pip install requests gdown mega.py gradio

    - name: Google Drive
      run: |
        python rvc/modules/model_management.py "https://drive.google.com/file/d/1lVQuCq5sQXRnAb_Z6m0nKb9305aePowy/view?usp=sharing" "test1"
        
    - name: HuggingFace
      run: |
        python rvc/modules/model_management.py "https://huggingface.co/Politrees/Victor_Tsoi/resolve/main/Victor_Tsoi.zip?download=true" "test2"

#    - name: Pixeldrain
#      run: |
#        python rvc/modules/model_management.py "" "test3"

#    - name: Mega
#      run: |
#        python rvc/modules/model_management.py "" "test4"

#    - name: Яндекс Диск
#      run: |
#        python rvc/modules/model_management.py "" "test5"
