name: Check Links

on:
  push:
    branches:
      - dev/PolGen-Lite
  pull_request:
    branches:
      - dev/PolGen-Lite

jobs:
  check-links:
    runs-on: ubuntu-latest

    steps:
    - name: Проверка кода
      uses: actions/checkout@v4

    - name: Настройка Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Установка зависимостей
      run: |
        pip install --upgrade pip==23.1
        pip install requests gdown mega.py gradio tenacity

    - name: Google Drive
      run: |
        python rvc/modules/model_management.py "https://drive.google.com/file/d/1lVQuCq5sQXRnAb_Z6m0nKb9305aePowy/view?usp=sharing" "test_model"
        
    - name: HuggingFace
      run: |
        python rvc/modules/model_management.py "https://huggingface.co/Politrees/Victor_Tsoi/resolve/main/Victor_Tsoi.zip?download=true" "test_model"


#    - name: Pixeldrain
#      run: |
#        python rvc/modules/model_management.py "" "test_model"

#    - name: Mega
#      run: |
#        python rvc/modules/model_management.py "" "test_model"

#    - name: Яндекс Диск
#      run: |
#        python rvc/modules/model_management.py "" "test_model"

#    - name: OneDrive
#      run: |
#        python rvc/modules/model_management.py "" "test_model"

    - name: Dropbox
      run: |
        python rvc/modules/model_management.py "https://www.dropbox.com/scl/fi/qgwb61xk365uoaled6s7b/Model.zip?rlkey=lljqcjqn8appak3jns5b6rc1r&st=tgyolk2w&dl=0" "test_model"

    - name: Box
      run: |
        python rvc/modules/model_management.py "https://app.box.com/s/gh08lk2wtmy893hz1n06uhl8jr7n29sg" "test_model"

    - name: MediaFire
      run: |
        python rvc/modules/model_management.py "https://www.mediafire.com/file/0cjw4ho9m2ap7z0/Model.zip/file" "test_model"

    - name: pCloud
      run: |
        python rvc/modules/model_management.py "https://e.pcloud.link/publink/show?code=XZTUsPZmjRlLDvPbAfEP7t4fvSHPYID49PV" "test_model"
